a = input('\033[31mDigite algo:')
print(f'Tipo primitivo: {type(a)}')
print(f'É alfabético: {a.isalpha()}')
print(f'É numérico: {a.isnumeric()}')
print(f'É alfanumérico: {a.isalnum()}')
print(f'Está todo maiúsculo: {a.isupper()}')
print(f'Está todo minúsculo: {a.islower()}')
print(f'É composto apenas por espaços: {a.isspace()}')
print(f'Está capitalizado: {a.istitle()}')
